<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEbPuWBg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEbPuWBg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEbPuWBg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEbPuWBg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEbPuWBg\App_KernelDevDebugContainer([
    'container.build_hash' => 'EbPuWBg',
    'container.build_id' => 'b9b08c2b',
    'container.build_time' => 1594669986,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEbPuWBg');
