<?php

namespace ContainerKQRk78y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdsScraperCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.App\Command\AdsScraperCommand' shared autowired service.
     *
     * @return \App\Command\AdsScraperCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/AdsScraperCommand.php';

        return $container->services['console.command.public_alias.App\\Command\\AdsScraperCommand'] = new \App\Command\AdsScraperCommand(NULL, ($container->privates['App\\Service\\AdsScraper'] ?? $container->load('getAdsScraperService')));
    }
}
